FROM public.ecr.aws/lambda/provided:al2

# Install 'sqlite' instead of 'sqlite-libs'
RUN yum update -y \
    && yum install -y sqlite \
    && yum clean all

COPY techdetector-linux-amd64 /var/runtime/bootstrap
RUN chmod +x /var/runtime/bootstrap

COPY queries.yaml /var/task/queries.yaml
