name: CI - Build Binary, Push Docker Image, and Create Release

permissions:
  contents: write
  id-token: write

env:
  AWS_REGION: eu-west-2
  IMAGE_NAME: techdetector-lambda
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    name: Test / Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Run Go Tests
        run: go test -race -covermode=atomic -coverprofile=coverage.out

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}